# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.srcs/sources_1/ip/realRAM/realRAM.xci
# IP: The module: 'realRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.gen/sources_1/ip/realRAM/realRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'realRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.srcs/sources_1/ip/realRAM/realRAM.xci
# IP: The module: 'realRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.gen/sources_1/ip/realRAM/realRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'realRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
