# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.srcs/sources_1/ip/lab4_3ROM/lab4_3ROM.xci
# IP: The module: 'lab4_3ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.gen/sources_1/ip/lab4_3ROM/lab4_3ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_3ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.srcs/sources_1/ip/lab4_3ROM/lab4_3ROM.xci
# IP: The module: 'lab4_3ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab4/lab4-test/lab4-test/lab4-test.gen/sources_1/ip/lab4_3ROM/lab4_3ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_3ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
