# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/myproject/verilog/lab4/lab4-test/A7.xdc

# IP: ip/Seg7_Dev_2/Seg7_Dev_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Seg7_Dev_2 || ORIG_REF_NAME==Seg7_Dev_2} -quiet] -quiet
