# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/myproject/verilog/lab2/SOC_system/SOC_system.srcs/sources_1/ip/ROM_D_0/ROM_D_0.xci
# IP: The module: 'ROM_D_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab2/SOC_system/SOC_system.gen/sources_1/ip/ROM_D_0/ROM_D_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/myproject/verilog/lab2/SOC_system/SOC_system.srcs/sources_1/ip/ROM_D_0/ROM_D_0.xci
# IP: The module: 'ROM_D_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab2/SOC_system/SOC_system.gen/sources_1/ip/ROM_D_0/ROM_D_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
