# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/myproject/verilog/lab4/lab4_int/SCPU_int/SCPU_int.srcs/sources_1/ip/whilenwe/whilenwe.xci
# IP: The module: 'whilenwe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab4/lab4_int/SCPU_int/SCPU_int.gen/sources_1/ip/whilenwe/whilenwe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'whilenwe'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/myproject/verilog/lab4/lab4_int/SCPU_int/SCPU_int.srcs/sources_1/ip/whilenwe/whilenwe.xci
# IP: The module: 'whilenwe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/myproject/verilog/lab4/lab4_int/SCPU_int/SCPU_int.gen/sources_1/ip/whilenwe/whilenwe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'whilenwe'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
